---
- name: Playbook to configure ansible controller organizations
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.tower_utilities
    - containers.podman
  vars:
    # builder_dir: /tmp
    ee_registry_dest: quay.io/your_place_here/ee_tools
    ee_name: ee_tools
    ee_bindep:
      - docker
    ee_python:
      - ansible-lint
      - ansible-builder
    ee_collections:
      - name: awx.awx
      - name: redhat_cop.tower_utilities
        version: 0.3.2-develh
      - name: containers.podman
      - name: community.docker
    ee_append:
      - VOLUME /var/lib/docker
  roles:
    - redhat_cop.tower_utilities.ee_builder
